# Nama Aplikasi
spring.application.name=CareVibe-be

# Konfigurasi H2 Database (In-Memory)
# Ganti baris datasource url yang lama dengan ini
spring.datasource.url=jdbc:h2:file:./carevibedb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Menatikan proteksi csrf default khusus untuk H2 Console agar bisa diakses
spring.h2.console.settings.web-allow-others=true